#!/bin/bash

MODE=${MODE:=client}

# If is a remote jar, download it
if [[ $MODE == "client" && $JAR =~ ^http ]]; then
  wget ${JAR} -O /tmp/download.jar
  JAR=/tmp/download.jar
fi

# Spark submit
spark-submit --class ${MAIN_CLASS} \
             --master ${MASTER} \
             ${SPARK_ARGS} \
             ${JAR} $@
